# Generated by Django 2.2.9 on 2022-03-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220304_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='пост№', max_length=200, verbose_name='название поста'),
        ),
    ]
